DROP TABLE IF EXISTS map_likes CASCADE;

CREATE TABLE map_likes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  date_liked TIMESTAMP NOT NULL
);